package com.swe.backend.service;

import java.io.ByteArrayOutputStream;
import java.util.Base64;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import com.swe.backend.model.CheckPaymentDto;
import com.swe.backend.model.SupplierInvoiceDto;
import com.swe.backend.repository.PaymentsRepository;
import com.swe.backend.repository.PaymentsRepository.PaymentPersistenceResult;

@Service
public class PaymentsService {
    private final PaymentsRepository paymentsRepository;

    public PaymentsService(PaymentsRepository paymentsRepository) {
        this.paymentsRepository = paymentsRepository;
    }

    public CheckPaymentDto generateSupplierCheck(long invoiceId, long generatedByUserId) {
        SupplierInvoiceDto invoice = paymentsRepository.findApprovedUnpaidInvoice(invoiceId)
            .orElseThrow(() -> new ResponseStatusException(
                HttpStatus.NOT_FOUND,
                "Approved unpaid invoice not found"
            ));

        double balance = paymentsRepository.currentCashBalance();
        if (balance < invoice.totalAmount()) {
            throw new ResponseStatusException(
                HttpStatus.BAD_REQUEST,
                "Insufficient funds. Check generation halted for manager review"
            );
        }

        String checkNumber = "CHK-" + System.currentTimeMillis();
        byte[] pdf = createCheckPdf(checkNumber, invoice);
        PaymentPersistenceResult persisted = paymentsRepository.persistCheckPayment(
            invoice,
            checkNumber,
            pdf,
            generatedByUserId
        );

        return new CheckPaymentDto(
            invoice.id(),
            persisted.checkNumber(),
            invoice.totalAmount(),
            persisted.createdAt(),
            Base64.getEncoder().encodeToString(pdf),
            persisted.cashBalanceAfterPayment()
        );
    }

    private byte[] createCheckPdf(String checkNumber, SupplierInvoiceDto invoice) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, out);
            document.open();
            document.add(new Paragraph("Supplier Check"));
            document.add(new Paragraph("Check No: " + checkNumber));
            document.add(new Paragraph("Invoice ID: " + invoice.id()));
            document.add(new Paragraph("Supplier: " + invoice.supplierName()));
            document.add(new Paragraph("Item Code: " + invoice.itemCode()));
            document.add(new Paragraph("Amount: " + invoice.totalAmount()));
            document.add(new Paragraph("Invoice Date: " + invoice.invoiceDate()));
            document.add(new Paragraph("Generated By: Restaurant System"));
        } catch (Exception ex) {
            throw new IllegalStateException("Failed to generate supplier check PDF", ex);
        } finally {
            document.close();
        }
        return out.toByteArray();
    }
}
